name: Upload Python package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - uses: yezz123/setup-uv@v4
        with:
          uv-venv: venv
      - name: Install dependencies
        run: uv pip install  -e . -r pyproject.toml --extra=dev build
      - name: Build package
        run: python -m build
      - name: Upload package distributions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
  release:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: release
      url: https://pypi.org/p/boomgate
    permissions:
      id-token: write
    steps:
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        name: dist
    - name: Publish GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        fail_on_unmatched_files: true
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
